import test from 'node:test';import assert from 'node:assert/strict';import {addMonths,due,complete,validateBackup} from '../src/domain.js';
const legacy=()=>({version:1,vehicles:[{id:'v',name:'M01',model:'Test',serial:'123',power:'Diesel',hours:500}],tasks:[{id:'t',vehicleId:'v',name:'Filtro olio',part:'F123',hours:250,months:6,lastHours:250,lastDate:'2026-01-31'}],history:[]});
const data=()=>validateBackup(legacy());
test('fine mese e anno bisestile',()=>{assert.equal(addMonths('2026-01-31',1),'2026-02-28');assert.equal(addMonths('2024-01-31',1),'2024-02-29');assert.equal(addMonths('2026-08-31',6),'2027-02-28')});
test('basta una soglia: ore o data, inclusa uguaglianza',()=>{const d=data();assert.equal(due(d.tasks[0],d.vehicles[0],'2026-04-01').status,'Scaduto');d.vehicles[0].reading=300;assert.equal(due(d.tasks[0],d.vehicles[0],'2026-07-31').status,'Scaduto');assert.equal(due(d.tasks[0],d.vehicles[0],'2026-07-05').status,'In scadenza');assert.equal(due(d.tasks[0],d.vehicles[0],'2026-04-01').status,'Regolare')});
test('frequenza solo ore non produce scadenza calendario',()=>{const d=data();d.tasks[0].months=0;assert.equal(due(d.tasks[0],d.vehicles[0]).day,null)});
test('registrazione aggiorna piano e contatore e conserva ricambi nello storico',()=>{const d=data();const r=complete(d,'v',['t'],{date:'2026-08-01',reading:520,cost:45,technician:'Mario',notes:''});assert.equal(r.tasks[0].lastReading,520);assert.equal(r.tasks[0].lastDate,'2026-08-01');assert.equal(r.history[0].items[0].part,'F123');assert.equal(d.vehicles[0].reading,500);assert.equal(validateBackup(r),r)});
test('rifiuta contatore arretrato, interventi sconosciuti e date precedenti al piano',()=>{const d=data();assert.throws(()=>complete(d,'v',['t'],{date:'2026-08-01',reading:499,cost:0}));assert.throws(()=>complete(d,'v',['x'],{date:'2026-08-01',reading:500,cost:0}));assert.throws(()=>complete(d,'v',['t'],{date:'2025-08-01',reading:500,cost:0}))});
test('backup con riferimenti mancanti, date inesistenti o senza frequenza viene respinto',()=>{let d=data();d.tasks[0].vehicleId='missing';assert.throws(()=>validateBackup(d));d=data();d.tasks[0].lastDate='2026-02-31';assert.throws(()=>validateBackup(d));d=data();d.tasks[0].interval=d.tasks[0].months=0;assert.throws(()=>validateBackup(d))});
test('migrazione v1 conserva contatori, scadenze e storico senza modificare l’originale',()=>{
 const old=legacy();old.history.push({id:'old',vehicleId:'v',vehicleName:'M01',date:'2026-01-31',hours:250,cost:30,technician:'Mario',notes:'Filtro sostituito',items:[{name:'Filtro olio',part:'F123'}]});
 const copy=structuredClone(old),next=validateBackup(old);
 assert.deepEqual(old,copy);assert.equal(next.version,2);assert.equal(next.vehicles[0].type,'forklift');assert.equal(next.vehicles[0].unit,'h');assert.equal(next.vehicles[0].reading,500);assert.equal(next.tasks[0].interval,250);assert.equal(next.tasks[0].lastReading,250);assert.equal(next.history[0].reading,250);assert.equal(next.history[0].unit,'h');assert.equal(next.history[0].items[0].part,'F123');assert.equal(validateBackup(next),next);
});
const car=()=>({version:2,vehicles:[{id:'car',type:'car',unit:'km',reading:64500,name:'Auto 01',model:'Modello',power:'Benzina',plate:'AB123CD',serial:''}],tasks:[{id:'oil',vehicleId:'car',name:'Tagliando',part:'',interval:15000,months:12,lastReading:50000,lastDate:'2026-01-01'}],history:[]});
test('auto: scadenza chilometrica e preavviso specifico per km',()=>{const d=car(),t=d.tasks[0],v=d.vehicles[0];assert.equal(due(t,v,'2026-04-01').reading,65000);assert.equal(due(t,v,'2026-04-01').status,'In scadenza');v.reading=65000;assert.equal(due(t,v,'2026-04-01').status,'Scaduto');v.reading=60000;assert.equal(due(t,v,'2026-04-01').status,'Regolare');assert.equal(due(t,v,'2027-01-01').status,'Scaduto')});
test('auto: registrazione conserva km e categoria, ricalcola da nuovo contatore',()=>{const d=car();const n=complete(d,'car',['oil'],{reading:65000,date:'2026-08-01',cost:190,technician:'Officina',notes:''});assert.equal(n.history[0].unit,'km');assert.equal(n.history[0].vehicleType,'car');assert.equal(due(n.tasks[0],n.vehicles[0],'2026-08-01').reading,80000);validateBackup(n);assert.throws(()=>complete(d,'car',['oil'],{reading:65000.5,date:'2026-08-01',cost:0}))});
test('trattori: ore decimali, archivio misto e controlli mensili senza intervallo contatore',()=>{const d=car(),v={id:'tr',type:'tractor',unit:'h',reading:1500.5,name:'Trattore 01',model:'Trattore',power:'Diesel',plate:'',serial:'TR001'};d.vehicles.push(v);const t={id:'hyd',vehicleId:'tr',name:'Filtro idraulico',part:'H01',interval:250,months:0,lastReading:1250,lastDate:'2026-01-01'};d.tasks.push(t);validateBackup(d);assert.equal(due(t,v,'2026-04-01').status,'Scaduto');t.interval=0;t.months=6;assert.equal(due(t,v,'2026-04-01').reading,null);assert.equal(due(t,v,'2026-07-01').status,'Scaduto');assert.equal(d.vehicles[0].reading,64500)});
test('backup v2 rifiuta categorie, unità e chilometri frazionari non validi',()=>{const d=car();d.vehicles[0].type='unknown';assert.throws(()=>validateBackup(d));d.vehicles[0].type='car';d.vehicles[0].unit='mile';assert.throws(()=>validateBackup(d));d.vehicles[0].unit='km';d.tasks[0].interval=.5;assert.throws(()=>validateBackup(d))});
