import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
const code=stripTypeScriptTypes(await readFile(new URL('../backend/supabase/functions/registration-email/index.ts',import.meta.url),'utf8'));
function worker(fetch){let handler;vm.runInNewContext(code,{Deno:{serve:f=>handler=f,env:{get:name=>name==='SUPABASE_URL'?'https://backend.test':'private-service-key'}},fetch,Response,AbortSignal,JSON,Number,Error,encodeURIComponent});return handler}
function request(body,origin='https://anto287.github.io'){return new Request('https://backend.test/function',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)})}
const valid={email:'owner@example.test',password:'a-secret-password'};
test('registration worker rejects invalid inputs and unexpected origins before privileged calls',async()=>{let calls=0;const run=worker(async()=>{calls++});assert.equal((await run(request(valid,'https://evil.test'))).status,403);assert.equal((await run(request({...valid,password:'short'}))).status,400);assert.equal((await run(request({...valid,password:'x'.repeat(3000)}))).status,413);assert.equal(calls,0)});
test('only configured recipient proceeds to generate a Supabase token',async()=>{const calls=[];const run=worker(async(url,opts)=>{calls.push(url);assert.equal(opts.headers.Authorization,'Bearer private-service-key');return Response.json({eligible:false})});const r=await run(request(valid));assert.deepEqual(await r.json(),{supported:false});assert.equal(calls.length,1)});
test('signup token is sent only by email and credentials never reach the browser response',async()=>{const calls=[];const hash='a'.repeat(64);const run=worker(async(url,opts)=>{calls.push(url);const body=JSON.parse(opts.body);if(url.endsWith('claim_registration_email'))return Response.json({eligible:true,key:'private-provider-key',sender:'LiftCare <onboarding@resend.dev>',attempt_id:'unique-attempt'});if(url.endsWith('generate_link')){assert.equal(body.type,'signup');assert.equal(body.password,valid.password);return Response.json({hashed_token:hash})}assert.equal(url,'https://api.resend.com/emails');assert.equal(opts.headers['Idempotency-Key'],'liftcare-confirm-unique-attempt');assert.equal(body.to[0],valid.email);assert.ok(body.text.includes('#token_hash='+hash+'&type=signup'));assert.ok(!body.text.includes(valid.password));return Response.json({id:'sent'})});const r=await run(request(valid));assert.equal(r.status,200);assert.deepEqual(await r.json(),{supported:true,sent:true});assert.equal(calls.length,3)});
test('provider failure is visible without leaking generated token',async()=>{const run=worker(async(url)=>url.endsWith('claim_registration_email')?Response.json({eligible:true,key:'private-key',sender:'sender',attempt_id:'id'}):url.endsWith('generate_link')?Response.json({hashed_token:'a'.repeat(64)}):Response.json({}, {status:403}));const r=await run(request(valid));assert.equal(r.status,502);assert.ok(!(await r.text()).includes('private-key'))});
