import {today,due,complete,validateBackup,blank,vehicleTypes,unitLabel,counterLabel} from './domain.js';
const KEY='liftcare-v1',app=document.querySelector('#app'),dialog=document.querySelector('#editor');let data=blank(),view='overview',filter='all',typeFilter='all',query='',startupError='';
try{const raw=localStorage.getItem(KEY);if(raw)data=validateBackup(JSON.parse(raw));}catch{startupError='Dati salvati non leggibili. Esporta una copia prima di inserire nuovi dati.';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);const date=s=>s?new Intl.DateTimeFormat('it-IT').format(new Date(s+'T12:00:00')):'—';
const vehicle=id=>data.vehicles.find(v=>v.id===id);const badge=s=>`<span class="badge ${s==='Scaduto'?'red':s==='In scadenza'?'amber':'green'}">${s}</span>`;
function toast(s){document.querySelector('#toast').textContent=s;document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),4000)}
function persist(next,recovery=false){if(startupError&&!recovery){toast("Esporta l’archivio non leggibile e importa un backup valido prima di modificare i dati.");return false}try{const checked=validateBackup(next);localStorage.setItem(KEY,JSON.stringify(checked));data=checked;render();return true}catch(error){toast(error instanceof DOMException?'Salvataggio non riuscito. Controlla lo spazio del browser.':error.message);return false}}
function rows(){return data.tasks.map(t=>({...t,v:vehicle(t.vehicleId),d:due(t,vehicle(t.vehicleId))})).filter(t=>(filter==='all'||t.vehicleId===filter)&&(typeFilter==='all'||t.v.type===typeFilter)&&`${t.name} ${t.v.name} ${t.v.model} ${t.v.plate} ${vehicleTypes[t.v.type]} ${t.part}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>({Scaduto:0,'In scadenza':1,Regolare:2}[a.d.status]-{Scaduto:0,'In scadenza':1,Regolare:2}[b.d.status]));}
function empty(title,text,action,label){return `<div class="empty"><span class="empty-icon">＋</span><h3>${title}</h3><p>${text}</p>${action?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`}
function render(){const all=data.tasks.map(t=>due(t,vehicle(t.vehicleId)));const late=all.filter(d=>d.status==='Scaduto').length,soon=all.filter(d=>d.status==='In scadenza').length;
app.innerHTML=`<aside><a class="brand" href="#"><span class="brand-mark">L</span>LiftCare</a><div class="aside-label">OFFICINA / FLOTTA</div><nav>${[['overview','▦','Panoramica'],['fleet','▤','Mezzi'],['plans','◷','Piani manutenzione'],['history','↺','Storico interventi']].map(([id,icon,name])=>`<button data-view="${id}" class="${view===id?'active':''}"><span>${icon}</span>${name}</button>`).join('')}</nav><div class="aside-bottom"><span class="live"></span> Archivio locale<div class="storage-text">Dati salvati su questo browser</div><button data-action="export">Esporta backup</button><button data-action="import">Importa backup</button></div></aside><main><header><div><span class="eyebrow">GESTIONE MANUTENZIONE</span><h1>${{overview:'La tua flotta, sotto controllo.',fleet:'Mezzi',plans:'Piani manutenzione',history:'Storico interventi'}[view]}</h1></div><button class="primary" data-action="${view==='fleet'?'vehicle':'service'}">＋ ${view==='fleet'?'Nuovo mezzo':'Registra intervento'}</button></header>${startupError?`<div class="warning">${startupError}</div>`:''}
${view==='overview'?`<section class="stats"><article><span>Mezzi in flotta</span><strong>${data.vehicles.length.toString().padStart(2,'0')}</strong><small>Muletti · Auto · Trattori</small></article><article class="alert-stat"><span>Interventi scaduti</span><strong>${late.toString().padStart(2,'0')}</strong><small>Da programmare</small></article><article><span>In scadenza</span><strong>${soon.toString().padStart(2,'0')}</strong><small>Per data, ore o chilometri</small></article><article><span>Costi registrati</span><strong class="cost">${money(data.history.reduce((n,h)=>n+h.cost,0))}</strong><small>${data.history.length} interventi eseguiti</small></article></section>`:''}
${view==='overview'||view==='plans'?`<section class="panel"><div class="panel-top"><div><h2>${view==='overview'?'Scadenziario':'Interventi programmati'}</h2><p>La prima soglia raggiunta, per data, ore o chilometri, determina la scadenza.</p></div><button data-action="plan">＋ Nuovo piano</button></div><div class="toolbar"><input id="search" placeholder="Cerca mezzo, targa o intervento…" aria-label="Cerca" value="${esc(query)}">${categorySelect()}<select id="filter" aria-label="Filtra mezzo"><option value="all">Tutti i mezzi</option>${data.vehicles.map(v=>`<option value="${esc(v.id)}" ${filter===v.id?'selected':''}>${esc(v.name)} · ${vehicleTypes[v.type]}</option>`).join('')}</select></div><div id="table">${taskTable()}</div></section><div class="hint">Gli intervalli vanno impostati secondo il manuale del costruttore e le condizioni di utilizzo.</div>`:''}
${view==='fleet'?`<div class="fleet-toolbar">${categorySelect()}</div>${fleetHTML()}`:''}${view==='history'?historyHTML():''}<footer>LiftCare <span>Manutenzione · Tagliandi · Ricambi</span></footer></main>`;
app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));
const category=app.querySelector('#category');if(category)category.onchange=e=>{typeFilter=e.target.value;render()};const search=app.querySelector('#search');if(search)search.oninput=e=>{query=e.target.value;app.querySelector('#table').innerHTML=taskTable();bindTable()};const select=app.querySelector('#filter');if(select)select.onchange=e=>{filter=e.target.value;render()};}
function taskTable(){const list=rows();return list.length?`<div class="table-scroll"><table><thead><tr><th>Mezzo / intervento</th><th>Stato</th><th>Prossima scadenza</th><th>Ultimo intervento</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><strong>${esc(t.name)}</strong><small>${esc(t.v.name)} · ${vehicleTypes[t.v.type]}${t.part?' · '+esc(t.part):''}</small></td><td>${badge(t.d.status)}</td><td><strong>${t.d.reading!==null?`${t.d.reading.toLocaleString('it-IT')} ${unitLabel(t.v)}`:''}${t.d.reading!==null&&t.d.day?' / ':''}${t.d.day?date(t.d.day):''}</strong><small>${t.d.remaining!==null?`${t.d.remaining>=0?'Mancano':'Superate'} ${Math.abs(t.d.remaining).toLocaleString('it-IT')} ${unitLabel(t.v)}`:'Scadenza a calendario'}</small></td><td>${date(t.lastDate)}<small>${t.lastReading.toLocaleString('it-IT')} ${unitLabel(t.v)}</small></td><td class="actions"><button data-action="service" data-id="${t.vehicleId}">Registra</button><button data-action="plan" data-id="${t.id}" aria-label="Modifica ${esc(t.name)}">Modifica</button></td></tr>`).join('')}</tbody></table></div>`:empty(data.tasks.length?'Nessun risultato':'Nessuna scadenza impostata',data.vehicles.length?'Aggiungi tagliandi, cambio olio, filtri e controlli con i tuoi intervalli.':'Inserisci il primo mezzo per iniziare a pianificare gli interventi.',data.vehicles.length?'plan':'vehicle',data.vehicles.length?'Crea piano':'Aggiungi mezzo');}
function bindTable(){app.querySelectorAll('#table [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))}
function categorySelect(){return `<select id="category" aria-label="Filtra categoria"><option value="all">Tutte le categorie</option>${Object.entries(vehicleTypes).map(([key,label])=>`<option value="${key}" ${typeFilter===key?'selected':''}>${label}</option>`).join('')}</select>`}
function fleetHTML(){const list=data.vehicles.filter(v=>typeFilter==='all'||v.type===typeFilter);return list.length?`<section class="fleet-grid">${list.map(v=>{const plans=data.tasks.filter(t=>t.vehicleId===v.id);const states=plans.map(t=>due(t,v).status);return `<article class="vehicle-card"><div class="card-top"><span class="vehicle-label">${vehicleTypes[v.type]} · ${esc(v.power)}</span>${plans.length?badge(states.includes('Scaduto')?'Scaduto':states.includes('In scadenza')?'In scadenza':'Regolare'):'<span class="badge neutral">Nessun piano</span>'}</div><h2>${esc(v.name)}</h2><p>${esc(v.model)}</p><div class="hour-meter"><strong>${v.reading.toLocaleString('it-IT')}</strong><span>${counterLabel(v).toLowerCase()}</span></div><dl><dt>Targa</dt><dd>${esc(v.plate)||'—'}</dd><dt>Matricola / telaio</dt><dd>${esc(v.serial)||'—'}</dd><dt>Piani attivi</dt><dd>${plans.length}</dd></dl><div class="card-actions"><button data-action="reading" data-id="${v.id}">Aggiorna ${v.unit==='km'?'km':'ore'}</button><button data-action="vehicle" data-id="${v.id}">Modifica</button></div></article>`}).join('')}</section>`:empty(data.vehicles.length?'Nessun mezzo in questa categoria':'La flotta parte da qui','Aggiungi muletti, auto e trattori con il rispettivo contatore.','vehicle','Aggiungi mezzo')}
function historyHTML(){return data.history.length?`<section class="panel"><div class="panel-top"><h2>Registro lavori</h2><button data-action="csv">Esporta CSV</button></div><div class="table-scroll"><table><thead><tr><th>Data / mezzo</th><th>Interventi e ricambi</th><th>Contatore</th><th>Tecnico e note</th><th>Costo</th></tr></thead><tbody>${data.history.map(h=>`<tr><td><strong>${date(h.date)}</strong><small>${esc(h.vehicleName)} · ${vehicleTypes[h.vehicleType]}</small></td><td>${h.items.map(i=>`<div>${esc(i.name)}${i.part?`<small>${esc(i.part)}</small>`:''}</div>`).join('')}</td><td>${h.reading.toLocaleString('it-IT')} ${h.unit}</td><td>${esc(h.technician)||'—'}<small>${esc(h.notes)}</small></td><td>${money(h.cost)}</td></tr>`).join('')}</tbody></table></div></section>`:empty('Nessun intervento registrato','Quando completi un tagliando, trovi qui lavori, ricambi e costi.','service','Registra intervento')}
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const options=selected=>data.vehicles.map(v=>`<option value="${v.id}" ${v.id===selected?'selected':''}>${esc(v.name)} · ${vehicleTypes[v.type]}</option>`).join('');
function modal(title,body,save,after){dialog.innerHTML=`<form><div class="modal-head"><h2>${title}</h2><button type="button" id="close" aria-label="Chiudi">×</button></div><div class="form-body">${body}<p id="form-error" role="alert"></p></div><div class="modal-foot"><button type="button" id="cancel">Annulla</button><button class="primary" type="submit">Salva</button></div></form>`;dialog.querySelector('#close').onclick=dialog.querySelector('#cancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));const next=save(f,e.target);if(persist(next)){dialog.close();toast('Salvato correttamente.')}}catch(err){dialog.querySelector('#form-error').textContent=err.message}};dialog.showModal();after?.();}
function action(kind,id){
 if(kind==='vehicle'){
  const v=vehicle(id)||{reading:0,type:typeFilter==='all'?'forklift':typeFilter,unit:typeFilter==='car'?'km':'h'};
  const locked=Boolean(id&&(data.tasks.some(t=>t.vehicleId===id)||data.history.some(h=>h.vehicleId===id)));
  modal(id?'Modifica mezzo':'Nuovo mezzo',`<label>Categoria<select name="type" id="vehicle-type">${Object.entries(vehicleTypes).map(([key,label])=>`<option value="${key}" ${v.type===key?'selected':''}>${label}</option>`).join('')}</select></label>${field('name','Nome / codice flotta',v.name,'text','required maxlength="80"')}${field('model','Marca e modello',v.model,'text','required maxlength="100"')}<div class="form-grid">${field('plate','Targa',v.plate,'text','maxlength="20"')}${field('serial','Matricola / telaio',v.serial,'text','maxlength="100"')}</div><label>Alimentazione<select name="power">${['Diesel','Benzina','GPL','Metano','Elettrico','Ibrido','Altro'].map(p=>`<option ${v.power===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Contatore<select name="unit" id="vehicle-unit" ${locked?'disabled':''}><option value="h" ${v.unit==='h'?'selected':''}>Ore di lavoro</option><option value="km" ${v.unit==='km'?'selected':''}>Chilometri</option></select></label>${locked?'<p class="help">L’unità del contatore è fissa perché sono già presenti piani o interventi.</p>':''}<div id="vehicle-reading">${field('reading',counterLabel(v)+' attuali',v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div>`,f=>{
    const n=structuredClone(data);const unit=locked?v.unit:f.unit;
    const entry={...f,unit,reading:Number(f.reading),id:id||crypto.randomUUID()};
    if(n.vehicles.some(x=>x.id!==id&&x.name.toLowerCase()===f.name.trim().toLowerCase()))throw Error('Nome già presente.');
    entry.name=f.name.trim();entry.plate=f.plate.trim().toUpperCase();
    if(!entry.name)throw Error('Inserisci un nome.');
    if(id&&unit===v.unit&&entry.reading<v.reading)throw Error('Il contatore non può diminuire.');
    if(id)n.vehicles[n.vehicles.findIndex(x=>x.id===id)]=entry;else n.vehicles.push(entry);return n;
  },()=>{
    const unit=dialog.querySelector('#vehicle-unit');
    const update=()=>{const same=unit.value===v.unit;dialog.querySelector('#vehicle-reading').innerHTML=field('reading',counterLabel({unit:unit.value})+' attuali',same?v.reading:0,'number',`required min="${same?v.reading:0}" step="${unit.value==='km'?1:0.1}"`)};
    unit.onchange=update;
    dialog.querySelector('#vehicle-type').onchange=e=>{if(!id&&!locked){unit.value=e.target.value==='car'?'km':'h';update()}};
  });
 }
 if(kind==='reading'){const v=vehicle(id);modal('Aggiorna contatore',`<p>${esc(v.name)} · Contatore attuale: ${v.reading.toLocaleString('it-IT')} ${unitLabel(v)}</p>${field('reading',counterLabel(v)+' attuali',v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}`,f=>{const n=structuredClone(data);n.vehicles.find(v=>v.id===id).reading=Number(f.reading);return n});}
 if(kind==='plan'){
  if(!data.vehicles.length){toast('Aggiungi prima un mezzo.');return}
  const t=data.tasks.find(t=>t.id===id)||{vehicleId:filter==='all'?data.vehicles.find(v=>typeFilter==='all'||v.type===typeFilter)?.id||data.vehicles[0].id:filter,interval:0,months:0,lastReading:0,lastDate:today()};
  const v=vehicle(t.vehicleId);
  const suggestions={forklift:['Tagliando completo','Cambio olio motore','Filtro olio','Filtro aria','Filtro carburante','Olio e filtro idraulico','Ingrassaggio','Controllo batteria','Controllo catene e forche'],car:['Tagliando completo','Cambio olio motore','Filtro olio','Filtro aria','Filtro abitacolo','Filtro carburante','Controllo freni','Cinghia distribuzione','Controllo pneumatici','Controllo batteria'],tractor:['Tagliando completo','Cambio olio motore','Filtro olio','Filtro aria','Filtro carburante','Olio e filtro idraulico','Olio trasmissione','Ingrassaggio','Controllo PTO','Controllo pneumatici']};
  const counterFields=v=>`<div class="form-grid">${field('interval',`Ogni ${v.unit==='km'?'chilometri':'ore'} (0 = disattivato)`,t.interval,'number',`required min="0" step="${v.unit==='km'?1:0.1}"`)}${field('months','Ogni mesi (0 = disattivato)',t.months,'number','required min="0" step="1"')}</div><p class="help">Imposta almeno una frequenza. Vale la soglia raggiunta prima: contatore o data.</p><div class="form-grid">${field('lastDate','Ultimo intervento / data iniziale',t.lastDate,'date',`required max="${today()}"`)}${field('lastReading',`${v.unit==='km'?'Km':'Ore'} ultimo intervento / iniziali`,t.lastReading,'number',`required min="0" max="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div>`;
  modal(id?'Modifica piano':'Nuovo piano manutenzione',`<label>Mezzo<select name="vehicleId" id="plan-vehicle" ${id?'disabled':''}>${options(t.vehicleId)}</select></label>${field('name','Intervento',t.name,'text','required list="jobs" maxlength="100"')}<datalist id="jobs"></datalist>${field('part','Codice ricambio / filtro',t.part,'text','maxlength="120"')}<div id="plan-counters">${counterFields(v)}</div>${id?'<button type="button" id="delete-plan" class="danger">Elimina piano</button>':''}`,f=>{
    const n=structuredClone(data);const entry={...f,vehicleId:id?t.vehicleId:f.vehicleId,id:id||crypto.randomUUID(),interval:Number(f.interval),months:Number(f.months),lastReading:Number(f.lastReading)};
    entry.name=entry.name.trim();if(!entry.name)throw Error('Inserisci un intervento.');if(!(entry.interval||entry.months))throw Error('Imposta una frequenza in ore, km o mesi.');
    if(entry.lastReading>vehicle(entry.vehicleId).reading)throw Error('Il contatore iniziale supera il valore attuale del mezzo.');
    if(id)n.tasks[n.tasks.findIndex(x=>x.id===id)]=entry;else n.tasks.push(entry);return n;
  },()=>{
    const updateJobs=v=>{dialog.querySelector('#jobs').innerHTML=suggestions[v.type].map(s=>`<option value="${s}">`).join('')};updateJobs(v);
    dialog.querySelector('#plan-vehicle').onchange=e=>{const next=vehicle(e.target.value);dialog.querySelector('#plan-counters').innerHTML=counterFields(next);updateJobs(next)};
    if(id)dialog.querySelector('#delete-plan').onclick=()=>{if(confirm('Eliminare questo piano? Lo storico degli interventi verrà conservato.')){const n=structuredClone(data);n.tasks=n.tasks.filter(x=>x.id!==id);if(persist(n))dialog.close()}};
  });
 }
 if(kind==='service'){
  if(!data.tasks.length){toast('Crea prima un piano manutenzione.');return}
  const selected=id||data.tasks[0].vehicleId;const v=vehicle(selected);
  modal('Registra intervento',`<label>Mezzo<select name="vehicleId" id="service-vehicle">${options(selected)}</select></label><div id="service-tasks"></div><div class="form-grid">${field('date','Data intervento',today(),'date',`required max="${today()}"`)}<div id="service-counter">${field('reading',`${v.unit==='km'?'Km':'Ore'} al momento dell’intervento`,v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div></div>${field('technician','Tecnico / officina','','text','maxlength="120"')}${field('cost','Costo totale (€)',0,'number','required min="0" step="0.01"')}<label>Note e ricambi utilizzati<textarea name="notes" rows="3" maxlength="2000"></textarea></label>`,(f,form)=>complete(data,f.vehicleId,[...form.querySelectorAll('[name="tasks"]:checked')].map(c=>c.value),{date:f.date,reading:Number(f.reading),cost:Number(f.cost),technician:f.technician,notes:f.notes}),()=>{
    const update=()=>{const vid=dialog.querySelector('#service-vehicle').value;const v=vehicle(vid);
      dialog.querySelector('#service-tasks').innerHTML=`<fieldset><legend>Lavori eseguiti</legend>${data.tasks.filter(t=>t.vehicleId===vid).map(t=>`<label class="check"><input type="checkbox" name="tasks" value="${t.id}"><span>${esc(t.name)}<small>${esc(t.part)}</small></span></label>`).join('')||'<p>Nessun piano per questo mezzo.</p>'}</fieldset>`;
      dialog.querySelector('#service-counter').innerHTML=field('reading',`${v.unit==='km'?'Km':'Ore'} al momento dell’intervento`,v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`);
    };dialog.querySelector('#service-vehicle').onchange=update;update();
  });
 }
 if(kind==='export'){download('liftcare-backup-'+today()+'.json',startupError?localStorage.getItem(KEY):JSON.stringify(data,null,2),'application/json');}
 if(kind==='import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>10000000)throw Error('Backup troppo grande (massimo 10 MB).');const next=validateBackup(JSON.parse(await file.text()));if(confirm('Importare il backup? I dati presenti saranno sostituiti. Esporta prima una copia se vuoi conservarli.')){if(persist(next,true)){startupError='';filter='all';typeFilter='all';render();toast('Backup importato.')}}}catch(e){toast(e.message)}};input.click();}
 if(kind==='csv'){const cell=s=>'"'+String(s).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Data','Mezzo','Categoria','Interventi','Ricambi','Contatore','Unità','Tecnico','Costo EUR','Note'],...data.history.map(h=>[h.date,h.vehicleName,vehicleTypes[h.vehicleType],h.items.map(i=>i.name).join(' | '),h.items.map(i=>i.part).join(' | '),h.reading,h.unit,h.technician,h.cost,h.notes])];download('liftcare-interventi.csv','\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.addEventListener('storage',e=>{if(e.key===KEY){try{data=e.newValue?validateBackup(JSON.parse(e.newValue)):blank();dialog.close();render();toast('Archivio aggiornato da un’altra scheda.')}catch{toast('Dati aggiornati non validi. Ricarica dopo aver verificato il backup.')}}});render();
