import {workSuggestions} from './jobs.js?v=7';
import {sendRegistration,confirmRegistration} from './auth.js?v=7';
import {api,saveSession,restoreSession,ensureSession,loadCloud,saveChanges,recordCloud,readPhotos,exportCloud,importCloud,retryPhotos,accessStatus,storageUsage} from './cloud.js?v=7';
import {today,due,complete,validateBackup,blank,MAX_PHOTOS,vehicleTypes,unitLabel,counterLabel} from './domain.js?v=7';
import {preparePhoto} from './photos.js?v=7';
const KEY='liftcare-v1',app=document.querySelector('#app'),dialog=document.querySelector('#editor');let data=blank(),view='overview',filter='all',typeFilter='all',query='',statusFilter='all',historyQuery='',startupError='';
let busy=false,pendingPhotoUpload=null,access={approved:false,is_admin:false},usage=null; // Existing local archive is preserved and imported only by explicit action.

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);const date=s=>s?new Intl.DateTimeFormat('it-IT').format(new Date(s+'T12:00:00')):'—';
const vehicle=id=>data.vehicles.find(v=>v.id===id);const badge=s=>`<span class="badge ${s==='Scaduto'?'red':s==='In scadenza'?'amber':'green'}">${s}</span>`;
function toast(s){document.querySelector('#toast').textContent=s;document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),4000)}
async function persist(next){try{data=next.cloudSaved?(next.data||blank()):await saveChanges(data,next);if(next.reloadError)startupError=next.reloadError;usage=await storageUsage().catch(()=>usage);render();return true}catch(error){toast('Salvataggio online non riuscito: '+error.message);try{data=await loadCloud();render()}catch{}return false}}

const icons={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',fleet:'<path d="M3 15V7h12v8M15 10h4l2 5v3h-3M3 18H2v-3h19M8 18h6"/><circle cx="6" cy="18" r="2"/><circle cx="16" cy="18" r="2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5 3 3 5-5"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-4v6l4 2"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',tool:'<path d="m14 6 4 4 3-3a6 6 0 0 1-8 8l-6 6-4-4 6-6a6 6 0 0 1 8-8z"/>',photo:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3v2m-1 3h.01"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>'};
const icon=(name)=>`<svg class="icon" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.tool}</svg>`;
const navigation=[['overview','home','Home'],['fleet','fleet','Mezzi'],['plans','calendar','Da fare'],['history','history','Lavori fatti']];
function navigate(next){view=next;query='';filter='all';statusFilter='all';render();window.scrollTo({top:0,behavior:'smooth'})}
function quickActions(){const ready=data.vehicles.length>0;return `<section class="quick-actions" aria-label="Azioni rapide"><button class="quick-card" data-action="vehicle"><span class="quick-icon">${icon('fleet')}</span><span><strong>Aggiungi un mezzo</strong><small>Muletto, auto o trattore</small></span>${icon('plus')}</button><button class="quick-card" data-action="${ready?'plan':'vehicle'}"><span class="quick-icon blue">${icon('calendar')}</span><span><strong>Programma un lavoro</strong><small>${ready?'Scegli cosa fare e quando':'Inizia aggiungendo un mezzo'}</small></span>${icon('arrow')}</button><button class="quick-card" data-action="${ready?'service':'vehicle'}"><span class="quick-icon orange">${icon('check')}</span><span><strong>Registra un lavoro</strong><small>${ready?'Scegli i lavori fatti e aggiungi foto':'Prima aggiungi il tuo primo mezzo'}</small></span>${icon('arrow')}</button></section>`}
function firstSteps(){return `<section class="first-steps"><div><span class="eyebrow">SI INIZIA DA QUI</span><h2>Tre piccoli passi. Tutto sotto controllo.</h2></div><ol>${[['vehicle','Aggiungi un mezzo','Dagli un nome e inserisci le ore o i km.',data.vehicles.length>0],['plan','Scegli i lavori','Olio, filtri e controlli: decidi ogni quanto.',data.tasks.length>0],['service','Segna il lavoro fatto','Aggiungi anche note e foto dei ricambi.',data.history.length>0]].map(([action,title,text,done],i)=>`<li class="${done?'done':''}"><span class="step-number">${done?icon('check'):i+1}</span><div><strong>${title}</strong><p>${text}</p></div></li>`).join('')}</ol></section>`}

function rows(){return data.tasks.map(t=>({...t,v:vehicle(t.vehicleId),d:due(t,vehicle(t.vehicleId))})).filter(t=>(statusFilter==='all'||t.d.status===statusFilter)&&(filter==='all'||t.vehicleId===filter)&&(typeFilter==='all'||t.v.type===typeFilter)&&`${t.name} ${t.v.name} ${t.v.model} ${t.v.plate} ${vehicleTypes[t.v.type]} ${t.part}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>({Scaduto:0,'In scadenza':1,Regolare:2}[a.d.status]-{Scaduto:0,'In scadenza':1,Regolare:2}[b.d.status]));}
function empty(title,text,action,label){return `<div class="empty"><span class="empty-icon">${icon('plus')}</span><h3>${title}</h3><p>${text}</p>${action?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`}
function render(){if(!api.session){dialog.close();dialog.innerHTML='';renderAuth(startupError);return}if(!access.approved){dialog.close();dialog.innerHTML='';renderPending();return}const all=data.tasks.map(t=>due(t,vehicle(t.vehicleId)));const late=all.filter(d=>d.status==='Scaduto').length,soon=all.filter(d=>d.status==='In scadenza').length;
const primaryAction=view==='fleet'||!data.vehicles.length?'vehicle':view==='plans'?'plan':'service';
app.innerHTML=`<aside><a class="brand" href="#" aria-label="LiftCare, vai alla home"><span class="brand-mark">${icon('tool')}</span>LiftCare<span class="brand-dot">.</span></a><p class="brand-caption">La manutenzione, semplice.</p><div class="aside-label">IL TUO SPAZIO</div><nav aria-label="Navigazione principale">${navigation.map(([id,glyph,name])=>`<button data-view="${id}" ${view===id?'aria-current="page"':''} class="${view===id?'active':''}">${icon(glyph)}<span>${name}</span></button>`).join('')}</nav><div class="aside-bottom"><div class="cloud-label"><span class="live"></span> Archivio online</div><div class="storage-text">${esc(api.session.user.email)}</div><button data-action="help" class="help-button">${icon('help')} Come si usa?</button><details class="settings"><summary>${icon('settings')} Account e backup</summary><div class="settings-content">${usage?`<div class="storage-meter"><label for="storage-progress">Foto: ${(usage.used_bytes/1000000).toFixed(1)} MB / 1.000 MB</label><progress id="storage-progress" value="${usage.used_bytes}" max="${usage.limit_bytes}"></progress>${usage.warning?`<p>${usage.blocked?'Spazio esaurito: nuovi allegati bloccati.':'Spazio oltre l’80%: esporta un backup e libera foto.'}</p>`:''}</div>`:''}<button data-action="refresh">Aggiorna dal cloud</button>${access.is_admin?'<button data-action="users">Approva utenti</button><button data-action="email-settings">Notifiche email</button>':''}<button data-action="migrate">Importa archivio di questo browser</button><button data-action="export">Esporta backup</button><button data-action="import">Importa backup</button><button data-action="logout">Esci dal tuo account</button></div></details></div></aside><main id="main-content"><header><div><span class="eyebrow">${view==='overview'?'BENVENUTO NELLA TUA OFFICINA':'LA TUA OFFICINA'}</span><h1>${{overview:'Meno pensieri. Più strada.',fleet:'I tuoi mezzi',plans:'I lavori da fare',history:'I lavori fatti'}[view]}</h1><p class="page-subtitle">${{overview:'Tutto quello che serve, a portata di un tocco.',fleet:'Contatori e manutenzione, mezzo per mezzo.',plans:'Scegli il lavoro. Al resto pensa il promemoria.',history:'Note, ricambi e foto. Ritrovi tutto qui.'}[view]}</p></div><button class="primary" data-action="${primaryAction}">${icon('plus')} ${primaryAction==='vehicle'?'Nuovo mezzo':primaryAction==='plan'?'Nuovo piano':'Registra intervento'}</button></header>${startupError?`<div class="warning" role="alert">${esc(startupError)}</div>`:''}${pendingPhotoUpload?'<div class="warning">Alcune foto attendono il caricamento. <button data-action="retry-photos">Riprova foto</button></div>':''}
${view==='overview'?`${quickActions()}${!data.history.length?firstSteps():''}<section class="stats" aria-label="La flotta in numeri"><button class="stat-card" data-go="fleet"><span>Mezzi in flotta</span><strong>${data.vehicles.length}</strong><small>Apri i tuoi mezzi ${icon('arrow')}</small></button><button class="stat-card alert-stat" data-status="Scaduto"><span>Da fare subito</span><strong>${late}</strong><small>Interventi scaduti ${icon('arrow')}</small></button><button class="stat-card soon-stat" data-status="In scadenza"><span>In arrivo</span><strong>${soon}</strong><small>Interventi in scadenza ${icon('arrow')}</small></button><button class="stat-card" data-go="history"><span>Spese registrate</span><strong class="cost">${money(data.history.reduce((n,h)=>n+h.cost,0))}</strong><small>${data.history.length} lavori fatti ${icon('arrow')}</small></button></section>`:''}
${view==='overview'||view==='plans'?`<section class="panel"><div class="panel-top"><div><h2>${view==='overview'?'Cosa c’è da fare?':'Il tuo programma'}</h2><p>Le scadenze si aggiornano con le ore, i km e la data.</p></div><button data-action="plan">${icon('plus')} Nuovo piano</button></div><div class="status-tabs" aria-label="Filtra per stato">${['all','Scaduto','In scadenza','Regolare'].map(st=>`<button data-status="${st}" aria-pressed="${statusFilter===st}" class="${statusFilter===st?'selected':''}">${{all:'Tutti',Scaduto:'Da fare subito','In scadenza':'In arrivo',Regolare:'Tutto ok'}[st]}</button>`).join('')}</div><div class="toolbar"><div class="search-field">${icon('search')}<input id="search" placeholder="Cerca un mezzo o un lavoro" aria-label="Cerca" value="${esc(query)}"></div>${categorySelect()}<select id="filter" aria-label="Filtra mezzo"><option value="all">Tutti i mezzi</option>${data.vehicles.map(v=>`<option value="${esc(v.id)}" ${filter===v.id?'selected':''}>${esc(v.name)} · ${vehicleTypes[v.type]}</option>`).join('')}</select></div><div id="table">${taskTable()}</div></section><div class="hint">Usa gli intervalli indicati nel manuale del tuo mezzo.</div>`:''}
${view==='fleet'?`<div class="fleet-toolbar">${categorySelect()}</div>${fleetHTML()}`:''}${view==='history'?historyHTML():''}<footer><span>LiftCare · Fatto per semplificarti la giornata.</span><span class="cloud-label"><span class="live"></span> Archivio privato</span></footer></main>`;
app.querySelector('.brand').onclick=e=>{e.preventDefault();navigate('overview')};app.querySelectorAll('[data-view],[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.view||b.dataset.go));app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));
app.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{statusFilter=b.dataset.status;view='plans';render()});
const category=app.querySelector('#category');if(category)category.onchange=e=>{typeFilter=e.target.value;render()};const search=app.querySelector('#search');if(search)search.oninput=e=>{query=e.target.value;app.querySelector('#table').innerHTML=taskTable();bindTable()};const select=app.querySelector('#filter');if(select)select.onchange=e=>{filter=e.target.value;render()};const hs=app.querySelector('#history-search');if(hs)hs.oninput=e=>{historyQuery=e.target.value;app.querySelector('#history-results').innerHTML=historyResults();app.querySelectorAll('#history-results [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))};}
function taskTable(){const list=rows();return list.length?`<div class="table-scroll"><table><thead><tr><th>Mezzo / intervento</th><th>Stato</th><th>Prossima scadenza</th><th>Ultimo intervento</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td data-label="Lavoro"><strong>${esc(t.name)}</strong><small>${esc(t.v.name)} · ${vehicleTypes[t.v.type]}${t.part?' · '+esc(t.part):''}</small></td><td data-label="Stato">${badge(t.d.status)}</td><td data-label="Prossima scadenza"><strong>${t.d.reading!==null?`${t.d.reading.toLocaleString('it-IT')} ${unitLabel(t.v)}`:''}${t.d.reading!==null&&t.d.day?' / ':''}${t.d.day?date(t.d.day):''}</strong><small>${t.d.remaining!==null?`${t.d.remaining>=0?'Mancano':'Superate'} ${Math.abs(t.d.remaining).toLocaleString('it-IT')} ${unitLabel(t.v)}`:'Scadenza a calendario'}</small></td><td data-label="Ultimo lavoro">${date(t.lastDate)}<small>${t.lastReading.toLocaleString('it-IT')} ${unitLabel(t.v)}</small></td><td class="actions"><button data-action="service" data-id="${t.vehicleId}">Registra</button><button data-action="plan" data-id="${t.id}" aria-label="Modifica ${esc(t.name)}">Modifica</button></td></tr>`).join('')}</tbody></table></div>`:empty(data.tasks.length?'Nessun lavoro da mostrare':'Nessuna scadenza impostata',data.vehicles.length?'Aggiungi tagliandi, cambio olio, filtri e controlli con i tuoi intervalli.':'Inserisci il primo mezzo per iniziare a pianificare gli interventi.',data.vehicles.length?'plan':'vehicle',data.vehicles.length?'Crea piano':'Aggiungi mezzo');}
function bindTable(){app.querySelectorAll('#table [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))}
function categorySelect(){return `<select id="category" aria-label="Filtra categoria"><option value="all">Tutte le categorie</option>${Object.entries(vehicleTypes).map(([key,label])=>`<option value="${key}" ${typeFilter===key?'selected':''}>${label}</option>`).join('')}</select>`}
function fleetHTML(){const list=data.vehicles.filter(v=>typeFilter==='all'||v.type===typeFilter);return list.length?`<section class="fleet-grid">${list.map(v=>{const plans=data.tasks.filter(t=>t.vehicleId===v.id);const states=plans.map(t=>due(t,v).status);return `<article class="vehicle-card"><div class="card-top"><span class="vehicle-label">${vehicleTypes[v.type]} · ${esc(v.power)}</span>${plans.length?badge(states.includes('Scaduto')?'Scaduto':states.includes('In scadenza')?'In scadenza':'Regolare'):'<span class="badge neutral">Nessun piano</span>'}</div><h2>${esc(v.name)}</h2><p>${esc(v.model)}</p><div class="hour-meter"><strong>${v.reading.toLocaleString('it-IT')}</strong><span>${counterLabel(v).toLowerCase()}</span></div><dl><dt>Targa</dt><dd>${esc(v.plate)||'—'}</dd><dt>Matricola / telaio</dt><dd>${esc(v.serial)||'—'}</dd><dt>Piani attivi</dt><dd>${plans.length}</dd></dl><div class="card-actions"><button data-action="reading" data-id="${v.id}">Aggiorna ${v.unit==='km'?'km':'ore'}</button><button data-action="vehicle" data-id="${v.id}">Modifica</button></div></article>`}).join('')}</section>`:empty(data.vehicles.length?'Nessun mezzo in questa categoria':'La flotta parte da qui','Aggiungi muletti, auto e trattori con il rispettivo contatore.','vehicle','Aggiungi mezzo')}
function historyResults(){const list=data.history.filter(h=>`${h.vehicleName} ${h.technician} ${h.notes} ${h.items.map(i=>i.name+' '+i.part).join(' ')}`.toLowerCase().includes(historyQuery.toLowerCase()));return list.length?`<div class="history-list">${list.map(h=>`<article class="history-card"><div class="history-date">${icon('check')}<span>${date(h.date)}</span></div><div class="history-work"><h3>${esc(h.vehicleName)} <span>${vehicleTypes[h.vehicleType]}</span></h3>${h.items.map(i=>`<p><strong>${esc(i.name)}</strong>${i.part?` <small>Ricambio: ${esc(i.part)}</small>`:''}</p>`).join('')}<div class="history-details"><span>${h.reading.toLocaleString('it-IT')} ${h.unit}</span>${h.technician?`<span>${esc(h.technician)}</span>`:''}</div>${h.notes?`<p class="history-notes">${esc(h.notes)}</p>`:''}</div><div class="history-cost"><strong>${money(h.cost)}</strong>${(h.photoFiles?.length||h.photos?.length)?`<button data-action="photos" data-id="${h.id}">${icon('photo')} Foto (${h.photoFiles?.length||h.photos.length})</button>`:''}</div></article>`).join('')}</div>`:empty('Nessun risultato','Prova con il nome del mezzo, del ricambio o del tecnico.');}
function historyHTML(){return data.history.length?`<section class="panel"><div class="panel-top"><div><h2>Il diario della tua flotta</h2><p>${data.history.length} lavori registrati, dal più recente.</p></div><button data-action="csv">Esporta CSV</button></div><div class="toolbar"><div class="search-field">${icon('search')}<input id="history-search" aria-label="Cerca nei lavori fatti" placeholder="Cerca mezzo, ricambio o nota" value="${esc(historyQuery)}"></div></div><div id="history-results">${historyResults()}</div></section>`:empty('Il tuo diario inizia dal primo lavoro','Registra un intervento per ritrovare qui note, ricambi e foto.','service','Registra intervento')}
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const options=selected=>data.vehicles.map(v=>`<option value="${v.id}" ${v.id===selected?'selected':''}>${esc(v.name)} · ${vehicleTypes[v.type]}</option>`).join('');
function modal(title,body,save,after){dialog.innerHTML=`<form><div class="modal-head"><h2>${title}</h2><button type="button" id="close" aria-label="Chiudi">×</button></div><div class="form-body">${body}<p id="form-error" role="alert"></p></div><div class="modal-foot"><button type="button" id="cancel">Annulla</button><button class="primary" type="submit">Salva</button></div></form>`;dialog.querySelector('#close').onclick=dialog.querySelector('#cancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const controls=[...e.target.querySelectorAll('button,input,select,textarea')];const disabled=controls.map(c=>c.disabled);try{const f=Object.fromEntries(new FormData(e.target));controls.forEach(c=>c.disabled=true);const next=await save(f,e.target);if(next.pendingPhotos?.length)pendingPhotoUpload={id:next.recordId,photos:next.pendingPhotos};if(await persist(next)){dialog.close();toast(next.photoError||'Salvato online.')}}catch(err){dialog.querySelector('#form-error').textContent=err.message}finally{busy=false;controls.forEach((c,i)=>c.disabled=disabled[i])}};dialog.showModal();after?.();}
async function action(kind,id,preset='',presetPart=''){
 try{
 if(kind==='help'){dialog.innerHTML=`<div class="modal-head"><h2>Una cosa alla volta.</h2><button id="close" aria-label="Chiudi">×</button></div><div class="form-body">${firstSteps()}<p>Usa <strong>Mezzi</strong> per aggiornare le ore o i km. In <strong>Da fare</strong> trovi i lavori in scadenza. In <strong>Lavori fatti</strong> ritrovi note e foto.</p><button class="primary" id="help-done">Ho capito</button></div>`;dialog.querySelector('#close').onclick=dialog.querySelector('#help-done').onclick=()=>dialog.close();dialog.showModal();return}
 if(kind==='users'){await showUsers();return}
 if(kind==='email-settings'){await showEmailSettings();return}
 if(kind==='logout'){try{await api.signOut()}finally{saveSession();data=blank();pendingPhotoUpload=null;dialog.close();render()}return}
 if(kind==='refresh'){data=await loadCloud();usage=await storageUsage();render();toast('Archivio online aggiornato.');return}
 if(kind==='retry-photos'){data=await retryPhotos(pendingPhotoUpload.id,pendingPhotoUpload.photos);pendingPhotoUpload=null;render();toast('Foto caricate.');return}
 if(kind==='migrate'){const raw=localStorage.getItem(KEY);if(!raw)throw Error('Nessun archivio locale in questo browser.');if(!confirm('Copiare l’archivio locale nel tuo account online? Il cloud deve essere vuoto. I dati locali rimangono conservati.'))return;const result=await importCloud(validateBackup(JSON.parse(raw)));data=result.data;render();toast(result.failures?'Dati importati; alcune foto non caricate. Conserva il backup locale.':'Archivio e foto importati online.');return}

 if(kind==='vehicle'){
  const v=vehicle(id)||{reading:0,type:typeFilter==='all'?'forklift':typeFilter,unit:typeFilter==='car'?'km':'h'};
  const locked=Boolean(id&&(data.tasks.some(t=>t.vehicleId===id)||data.history.some(h=>h.vehicleId===id)));
  modal(id?'Modifica mezzo':'Nuovo mezzo',`<label>Categoria<select name="type" id="vehicle-type">${Object.entries(vehicleTypes).map(([key,label])=>`<option value="${key}" ${v.type===key?'selected':''}>${label}</option>`).join('')}</select></label>${field('name','Nome / codice flotta',v.name,'text','required maxlength="80"')}${field('model','Marca e modello',v.model,'text','required maxlength="100"')}<div class="form-grid">${field('plate','Targa',v.plate,'text','maxlength="20"')}${field('serial','Matricola / telaio',v.serial,'text','maxlength="100"')}</div><label>Alimentazione<select name="power">${['Diesel','Benzina','GPL','Metano','Elettrico','Ibrido','Altro'].map(p=>`<option ${v.power===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Contatore<select name="unit" id="vehicle-unit" ${locked?'disabled':''}><option value="h" ${v.unit==='h'?'selected':''}>Ore di lavoro</option><option value="km" ${v.unit==='km'?'selected':''}>Chilometri</option></select></label>${locked?'<p class="help">L’unità del contatore è fissa perché sono già presenti piani o interventi.</p>':''}<div id="vehicle-reading">${field('reading',counterLabel(v)+' attuali',v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div>`,f=>{
    const n=structuredClone(data);const unit=locked?v.unit:f.unit;
    const entry={...f,unit,reading:Number(f.reading),id:id||crypto.randomUUID()};
    if(n.vehicles.some(x=>x.id!==id&&x.name.toLowerCase()===f.name.trim().toLowerCase()))throw Error('Nome già presente.');
    entry.name=f.name.trim();entry.plate=f.plate.trim().toUpperCase();
    if(!entry.name)throw Error('Inserisci un nome.');
    if(id&&unit===v.unit&&entry.reading<v.reading)throw Error('Il contatore non può diminuire.');
    if(id)n.vehicles[n.vehicles.findIndex(x=>x.id===id)]=entry;else n.vehicles.push(entry);return n;
  },()=>{
    const unit=dialog.querySelector('#vehicle-unit');
    const update=()=>{const same=unit.value===v.unit;dialog.querySelector('#vehicle-reading').innerHTML=field('reading',counterLabel({unit:unit.value})+' attuali',same?v.reading:0,'number',`required min="${same?v.reading:0}" step="${unit.value==='km'?1:0.1}"`)};
    unit.onchange=update;
    dialog.querySelector('#vehicle-type').onchange=e=>{if(!id&&!locked){unit.value=e.target.value==='car'?'km':'h';update()}};
  });
 }
 if(kind==='reading'){const v=vehicle(id);modal('Aggiorna contatore',`<p>${esc(v.name)} · Contatore attuale: ${v.reading.toLocaleString('it-IT')} ${unitLabel(v)}</p>${field('reading',counterLabel(v)+' attuali',v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}`,f=>{const n=structuredClone(data);n.vehicles.find(v=>v.id===id).reading=Number(f.reading);return n});}
 if(kind==='plan'){
  if(!data.vehicles.length){toast('Aggiungi prima un mezzo.');return}
  const t=data.tasks.find(t=>t.id===id)||{vehicleId:filter==='all'?data.vehicles.find(v=>typeFilter==='all'||v.type===typeFilter)?.id||data.vehicles[0].id:filter,interval:0,months:0,lastReading:0,lastDate:today()};
  const v=vehicle(t.vehicleId);
  const suggestions=workSuggestions;
  const counterFields=v=>`<div class="form-grid">${field('interval',`Ogni ${v.unit==='km'?'chilometri':'ore'} (0 = disattivato)`,t.interval,'number',`required min="0" step="${v.unit==='km'?1:0.1}"`)}${field('months','Ogni mesi (0 = disattivato)',t.months,'number','required min="0" step="1"')}</div><p class="help">Imposta almeno una frequenza. Vale la soglia raggiunta prima: contatore o data.</p><div class="form-grid">${field('lastDate','Ultimo intervento / data iniziale',t.lastDate,'date',`required max="${today()}"`)}${field('lastReading',`${v.unit==='km'?'Km':'Ore'} ultimo intervento / iniziali`,t.lastReading,'number',`required min="0" max="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div>`;
  modal(id?'Modifica piano':'Nuovo piano manutenzione',`${!id?'<div class="intent-switch"><span>Vuoi segnare un lavoro già fatto?</span><button type="button" id="service-instead">✓ Registra lavoro e foto</button></div><p class="help">Questo piano serve a ricordarti i lavori futuri.</p>':''}<label>Mezzo<select name="vehicleId" id="plan-vehicle" ${id?'disabled':''}>${options(t.vehicleId)}</select></label>${field('name','Intervento',t.name,'text','required list="jobs" maxlength="100"')}<datalist id="jobs"></datalist><div id="job-choices" class="job-choices" aria-label="Lavori più usati"></div>${field('part','Codice ricambio / filtro',t.part,'text','maxlength="120"')}<div id="plan-counters">${counterFields(v)}</div>${id?'<button type="button" id="delete-plan" class="danger">Elimina piano</button>':''}`,f=>{
    const n=structuredClone(data);const entry={...f,vehicleId:id?t.vehicleId:f.vehicleId,id:id||crypto.randomUUID(),interval:Number(f.interval),months:Number(f.months),lastReading:Number(f.lastReading)};
    entry.name=entry.name.trim();if(!entry.name)throw Error('Inserisci un intervento.');if(!(entry.interval||entry.months))throw Error('Imposta una frequenza in ore, km o mesi.');
    if(entry.lastReading>vehicle(entry.vehicleId).reading)throw Error('Il contatore iniziale supera il valore attuale del mezzo.');
    if(id)n.tasks[n.tasks.findIndex(x=>x.id===id)]=entry;else n.tasks.push(entry);return n;
  },()=>{
    if(!id)dialog.querySelector('#service-instead').onclick=()=>{const selected=dialog.querySelector('#plan-vehicle').value;const name=dialog.querySelector('[name=name]').value.trim();const part=dialog.querySelector('[name=part]').value.trim();dialog.close();action('service',selected,name,part)};
    const updateJobs=v=>{dialog.querySelector('#jobs').innerHTML=suggestions[v.type].map(s=>`<option value="${s}">`).join('');dialog.querySelector('#job-choices').innerHTML=suggestions[v.type].slice(0,6).map(name=>`<button type="button" data-job="${esc(name)}">${esc(name)}</button>`).join('');dialog.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{dialog.querySelector('[name="name"]').value=b.dataset.job;dialog.querySelectorAll('[data-job]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))})};updateJobs(v);
    dialog.querySelector('#plan-vehicle').onchange=e=>{const next=vehicle(e.target.value);dialog.querySelector('#plan-counters').innerHTML=counterFields(next);updateJobs(next)};
    if(id)dialog.querySelector('#delete-plan').onclick=()=>{if(confirm('Eliminare questo piano? Lo storico degli interventi verrà conservato.')){const n=structuredClone(data);n.tasks=n.tasks.filter(x=>x.id!==id);persist(n).then(ok=>{if(ok)dialog.close()})}};
  });
 }
 if(kind==='service'){
  if(!data.vehicles.length){toast('Aggiungi prima un mezzo.');return}
  const selected=id||(filter!=='all'?filter:data.vehicles.find(v=>typeFilter==='all'||v.type===typeFilter)?.id)||data.vehicles[0].id;const v=vehicle(selected);let photos=[];
  modal('Registra intervento',`<p class="help">Seleziona uno o più lavori fatti. Puoi aggiungere le foto dei lavori e dei ricambi: non serve un piano.</p><label>Mezzo<select name="vehicleId" id="service-vehicle">${options(selected)}</select></label><div id="service-tasks"></div><div class="form-grid">${field('date','Data intervento',today(),'date',`required max="${today()}"`)}<div id="service-counter">${field('reading',`${v.unit==='km'?'Km':'Ore'} al momento dell’intervento`,v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`)}</div></div>${field('technician','Tecnico / officina','','text','maxlength="120"')}${field('cost','Costo totale (€)',0,'number','required min="0" step="0.01"')}<label>Note e ricambi utilizzati<textarea name="notes" rows="3" maxlength="2000"></textarea></label><fieldset><legend>Foto allegate a note e ricambi</legend><label>Aggiungi foto<input id="service-photos" type="file" accept="image/*" multiple></label><label>Scatta una foto<input id="camera-photo" type="file" accept="image/*" capture="environment"></label><p class="help">Fino a 6 foto, compresse automaticamente. Salvate nel tuo archivio online privato e nel backup JSON.</p><div id="photo-previews" class="photo-grid"></div><p id="photo-status" class="help" role="status"></p></fieldset>`,(f,form)=>{const planIds=[...form.querySelectorAll('[name="tasks"]:checked')].map(c=>c.value);const items=[...form.querySelectorAll('[name=extra-work]:checked')].map(c=>({name:c.dataset.name,part:c.dataset.part||''}));complete(data,f.vehicleId,planIds,{date:f.date,reading:Number(f.reading),cost:Number(f.cost),technician:f.technician,notes:f.notes,photos,items});return recordCloud({machineId:f.vehicleId,planIds,items,date:f.date,reading:Number(f.reading),cost:Number(f.cost),technician:f.technician,notes:f.notes},photos)},()=>{
    const preview=()=>{dialog.querySelector('#photo-previews').innerHTML=photos.map((p,i)=>`<figure><img src="${esc(p.dataUrl)}" alt="${esc(p.name)}"><figcaption>${esc(p.name)}</figcaption><button type="button" data-remove-photo="${i}" aria-label="Rimuovi ${esc(p.name)}">Rimuovi</button></figure>`).join('');dialog.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>{photos.splice(Number(b.dataset.removePhoto),1);preview()})};
    const add=async e=>{const input=e.target,form=input.closest('form'),files=[...input.files];input.value='';if(!files.length)return;const error=form.querySelector('#form-error');error.textContent='';if(photos.length+files.length>MAX_PHOTOS){error.textContent='Puoi allegare al massimo 6 foto. Rimuovine una prima di aggiungerne altre.';return}const controls=[...form.querySelectorAll('button[type="submit"],#service-photos,#camera-photo')];controls.forEach(b=>b.disabled=true);form.querySelector('#photo-status').textContent='Preparazione foto…';try{const added=[];for(const file of files)added.push(await preparePhoto(file));if(input.isConnected){photos.push(...added);preview()}}catch(err){error.textContent=err.message}finally{controls.forEach(b=>b.disabled=false);form.querySelector('#photo-status').textContent=''}};
    dialog.querySelector('#service-photos').onchange=add;dialog.querySelector('#camera-photo').onchange=add;
    const update=()=>{const vid=dialog.querySelector('#service-vehicle').value;const v=vehicle(vid);
      const plans=data.tasks.filter(t=>t.vehicleId===vid);const names=new Set(plans.map(t=>t.name.toLowerCase()));const suggestions=workSuggestions[v.type].filter(name=>!names.has(name.toLowerCase()));
      dialog.querySelector('#service-tasks').innerHTML=`<fieldset><legend>Cosa hai fatto?</legend><div class="work-checks">${plans.map(t=>`<label class="check"><input type="checkbox" name="tasks" value="${t.id}" ${preset.toLowerCase()===t.name.toLowerCase()?'checked':''}><span>${esc(t.name)}<small>${esc(t.part)||'Aggiorna anche la prossima scadenza'}</small></span></label>`).join('')}${suggestions.map(name=>`<label class="check"><input type="checkbox" name="extra-work" data-name="${esc(name)}" data-part="${preset.toLowerCase()===name.toLowerCase()?esc(presetPart):''}" ${preset.toLowerCase()===name.toLowerCase()?'checked':''}><span>${esc(name)}</span></label>`).join('')}</div><details class="custom-work"><summary>＋ Aggiungi un altro lavoro / ricambio</summary>${field('extraName','Nome del lavoro','','text','maxlength="100"')}${field('extraPart','Codice ricambio','','text','maxlength="120"')}<button type="button" id="add-custom-work">Aggiungi alla selezione</button></details><p id="selection-count" class="help" role="status"></p></fieldset>`;
      const count=()=>{const n=dialog.querySelectorAll('[name=tasks]:checked,[name=extra-work]:checked').length;dialog.querySelector('#selection-count').textContent=n?`${n} ${n===1?'lavoro selezionato':'lavori selezionati'}`:'Tocca i lavori che hai eseguito.'};dialog.querySelector('#service-tasks').onchange=count;
      const addCustom=(name,part='')=>{const inputs=[...dialog.querySelectorAll('[name=tasks],[name=extra-work]')];const existing=inputs.find(c=>(c.dataset.name||plans.find(t=>t.id===c.value)?.name||'').toLowerCase()===name.toLowerCase());if(existing){existing.checked=true;count();return}const label=document.createElement('label');label.className='check';label.innerHTML=`<input type="checkbox" name="extra-work" data-name="${esc(name)}" data-part="${esc(part)}" checked><span>${esc(name)}<small>${esc(part)}</small></span>`;dialog.querySelector('.work-checks').append(label);count()};
      dialog.querySelector('#add-custom-work').onclick=()=>{const name=dialog.querySelector('[name=extraName]').value.trim(),part=dialog.querySelector('[name=extraPart]').value.trim();if(!name){dialog.querySelector('#form-error').textContent='Inserisci il nome del lavoro.';return}dialog.querySelector('#form-error').textContent='';addCustom(name,part);dialog.querySelector('[name=extraName]').value='';dialog.querySelector('[name=extraPart]').value=''};
      if(preset&&!plans.some(t=>t.name.toLowerCase()===preset.toLowerCase())&&!suggestions.some(name=>name.toLowerCase()===preset.toLowerCase()))addCustom(preset,presetPart);count();
      dialog.querySelector('#service-counter').innerHTML=field('reading',`${v.unit==='km'?'Km':'Ore'} al momento dell’intervento`,v.reading,'number',`required min="${v.reading}" step="${v.unit==='km'?1:0.1}"`);
    };dialog.querySelector('#service-vehicle').onchange=update;update();
  });
 }
 if(kind==='photos'){const h=data.history.find(h=>h.id===id);if(!h)return;const gallery=await readPhotos(h);if(!gallery.length)return;dialog.innerHTML=`<div class="modal-head"><h2>Foto intervento · ${date(h.date)}</h2><button id="close" aria-label="Chiudi">×</button></div><div class="form-body photo-gallery">${gallery.map(p=>`<figure><img src="${esc(p.dataUrl)}" alt="${esc(p.name)}"><figcaption>${esc(p.name)}</figcaption><a href="${esc(p.dataUrl)}" download="${esc(p.name)}">Scarica foto</a></figure>`).join('')}</div>`;dialog.querySelector('#close').onclick=()=>dialog.close();dialog.showModal();}
 if(kind==='export'){download('liftcare-backup-'+today()+'.json',JSON.stringify(await exportCloud(data),null,2),'application/json');}
 if(kind==='import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>200000000)throw Error('Backup troppo grande (massimo 200 MB).');const next=validateBackup(JSON.parse(await file.text()));if(confirm('Importare il backup nel tuo account? Il cloud deve essere vuoto.')){const result=await importCloud(next);data=result.data;filter='all';typeFilter='all';render();toast(result.failures?'Dati importati; alcune foto non caricate. Conserva il backup.':'Backup importato online.')}}catch(e){toast(e.message)}};input.click();}
 if(kind==='csv'){const cell=s=>'"'+String(s).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Data','Mezzo','Categoria','Interventi','Ricambi','Contatore','Unità','Tecnico','Costo EUR','Note'],...data.history.map(h=>[h.date,h.vehicleName,vehicleTypes[h.vehicleType],h.items.map(i=>i.name).join(' | '),h.items.map(i=>i.part).join(' | '),h.reading,h.unit,h.technician,h.cost,h.notes])];download('liftcare-interventi.csv','\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
}catch(e){toast(e.message)}
}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function renderAuth(message=''){
 app.innerHTML=`<main class="auth-main"><section class="panel auth-panel"><span class="eyebrow">LIFTCARE · ARCHIVIO PRIVATO</span><div class="auth-brand"><span class="brand-mark">${icon('tool')}</span>LiftCare.</div><h1>Accedi alla tua flotta</h1><p>Mezzi, manutenzioni e foto sincronizzati tra i tuoi dispositivi.</p><form id="auth-form">${field('email','Email','','email','required autocomplete="username"')}${field('password','Password','','password','required minlength="8" autocomplete="current-password"')}<p id="auth-error" class="${message.startsWith('Email inviata')?'success-message':''}" role="alert">${esc(message)}</p><button type="button" id="show-password" class="text-button" aria-pressed="false">Mostra password</button><button class="primary" type="submit">Accedi ${icon('arrow')}</button><button type="button" id="signup">Crea account</button></form><p class="help">Registrazione con conferma email e approvazione dell’admin. Ogni account ha un archivio separato. La sessione resta attiva in questa scheda fino alla chiusura o all’uscita.</p><details class="auth-extra"><summary>Hai già usato LiftCare?</summary><button id="local-backup">Scarica il vecchio backup locale</button></details></section></main>`;
 const form=app.querySelector('#auth-form');app.querySelector('#show-password').onclick=e=>{const password=form.querySelector('[name=password]');const shown=password.type==='password';password.type=shown?'text':'password';e.target.textContent=shown?'Nascondi password':'Mostra password';e.target.setAttribute('aria-pressed',String(shown))};
 const authenticate=async signup=>{if(!form.reportValidity())return;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const {email,password}=Object.fromEntries(new FormData(form));try{if(signup){await sendRegistration(api,email,password);renderAuth('Email inviata. Apri il messaggio e premi il link per confermare il tuo account.');return}await api.signIn(email,password);startupError='';saveSession();access=await accessStatus();data=access.approved?await loadCloud():blank();usage=access.approved?await storageUsage():null;render()}catch(e){if(api.session){await api.signOut().catch(()=>{});saveSession();data=blank()}form.querySelector('#auth-error').textContent=e.message}finally{buttons.forEach(b=>b.disabled=false)}};
 form.onsubmit=e=>{e.preventDefault();authenticate(false)};app.querySelector('#signup').onclick=()=>authenticate(true);app.querySelector('#local-backup').onclick=()=>{const raw=localStorage.getItem(KEY);if(raw)download('liftcare-backup-locale.json',raw,'application/json');else toast('Nessun archivio locale in questo browser.')};
}
try{if(await confirmRegistration(api,window.location,window.history))saveSession();else await restoreSession()}catch(e){startupError='Conferma non riuscita: '+e.message;api.session=null;saveSession()}if(api.session){try{access=await accessStatus();if(access.approved){data=await loadCloud();usage=await storageUsage()}}catch(e){startupError='Caricamento online non riuscito: '+e.message}}render();
window.addEventListener('hashchange',async()=>{try{if(!await confirmRegistration(api,window.location,window.history))return;saveSession();startupError='';access=await accessStatus();data=access.approved?await loadCloud():blank();usage=access.approved?await storageUsage():null;render();toast('Email confermata. Benvenuto in LiftCare.')}catch(e){startupError='Conferma non riuscita: '+e.message;render()}});
setInterval(async()=>{if(api.session&&!busy&&!dialog.open){try{await ensureSession();access=await accessStatus();data=access.approved?await loadCloud():blank();usage=access.approved?await storageUsage():null;startupError='';render()}catch(e){startupError='Connessione online da verificare: '+e.message;render()}}},60000);

function renderPending(){app.innerHTML=`<main class="auth-main"><section class="panel auth-panel"><h1>Accesso in attesa</h1><p>${esc(api.session.user.email)}</p><p>L’admin deve approvare il tuo account prima che tu possa usare il gestionale. Dati e foto sono bloccati dal backend.</p><button id="check-approval" class="primary">Controlla approvazione</button><button id="pending-logout">Esci</button></section></main>`;app.querySelector('#check-approval').onclick=async()=>{try{access=await accessStatus();data=access.approved?await loadCloud():blank();usage=access.approved?await storageUsage():null;render();if(!access.approved)toast('Approvazione ancora in attesa.')}catch(e){toast(e.message)}};app.querySelector('#pending-logout').onclick=()=>action('logout')}
async function showUsers(){await ensureSession();const users=await api.request('/rest/v1/rpc/list_access_requests',{method:'POST',body:{}});dialog.innerHTML=`<div class="modal-head"><h2>Accesso utenti</h2><button id="close">×</button></div><div class="form-body"><p>Le autorizzazioni vengono verificate dal server a ogni richiesta. Puoi configurare le notifiche dal pulsante Notifiche email.</p>${users.map(u=>`<p><strong>${esc(u.email)}</strong> · ${u.is_admin?'Admin':u.approved?'Approvato':'In attesa'} ${u.is_admin?'':`<button data-user="${esc(u.user_id)}" data-allow="${!u.approved}">${u.approved?'Revoca accesso':'Approva'}</button>`}</p>`).join('')}</div>`;dialog.querySelector('#close').onclick=()=>dialog.close();dialog.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api.request('/rest/v1/rpc/set_user_approval',{method:'POST',body:{target_user:b.dataset.user,allow_access:b.dataset.allow==='true'}});await showUsers()}catch(e){toast(e.message);b.disabled=false}});if(!dialog.open)dialog.showModal()}

async function showEmailSettings(){await ensureSession();const status=await api.request('/rest/v1/rpc/email_status',{method:'POST',body:{}});dialog.innerHTML=`<div class="modal-head"><h2>Notifiche email</h2><button id="close" aria-label="Chiudi">×</button></div><form id="email-settings-form" class="form-body"><p>${status.configured?'Servizio configurato':'Invio non ancora attivo'} · ${status.pending} richieste in coda · ${status.sent} email inviate${status.failed?` · ${status.failed} invii da riprovare`:''}</p><p>Destinatario admin: ${esc(status.recipient)}</p><p class="help">Usa un account Resend Free. Per inviare solo a te stesso non serve acquistare un dominio: crea Resend con la stessa email admin e usa il mittente onboarding@resend.dev. La chiave resta cifrata sul server; non viene salvata nel browser o nella repository.</p>${field('resend_key','Chiave API Resend','','password','required autocomplete="off"')}${field('sender','Mittente',status.sender||'LiftCare <onboarding@resend.dev>','text','required maxlength="200"')}<p id="email-error" role="alert"></p><button class="primary" type="submit">Salva e invia richieste in coda</button></form>`;dialog.querySelector('#close').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target;const f=Object.fromEntries(new FormData(form));const button=form.querySelector('button');button.disabled=true;try{await api.request('/rest/v1/rpc/configure_email',{method:'POST',body:f});form.querySelector('[name="resend_key"]').value='';dialog.close();toast('Configurazione salvata. Gli invii sono in coda; controlla la consegna nel servizio email.')}catch(err){form.querySelector('#email-error').textContent=err.message}finally{button.disabled=false}};dialog.showModal()}
