import {today,due,complete,validateBackup,blank} from './domain.js';
const KEY='liftcare-v1',app=document.querySelector('#app'),dialog=document.querySelector('#editor');let data=blank(),view='overview',filter='all',query='',startupError='';
try{const raw=localStorage.getItem(KEY);if(raw)data=validateBackup(JSON.parse(raw));}catch{startupError='Dati salvati non leggibili. Esporta una copia prima di inserire nuovi dati.';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);const date=s=>s?new Intl.DateTimeFormat('it-IT').format(new Date(s+'T12:00:00')):'—';
const vehicle=id=>data.vehicles.find(v=>v.id===id);const badge=s=>`<span class="badge ${s==='Scaduto'?'red':s==='In scadenza'?'amber':'green'}">${s}</span>`;
function toast(s){document.querySelector('#toast').textContent=s;document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),4000)}
function persist(next,recovery=false){if(startupError&&!recovery){toast("Esporta l’archivio non leggibile e importa un backup valido prima di modificare i dati.");return false}try{localStorage.setItem(KEY,JSON.stringify(next));data=next;render();return true}catch{toast('Salvataggio non riuscito. Controlla lo spazio del browser.');return false}}
function rows(){return data.tasks.map(t=>({...t,v:vehicle(t.vehicleId),d:due(t,vehicle(t.vehicleId))})).filter(t=>(filter==='all'||t.vehicleId===filter)&&`${t.name} ${t.v.name} ${t.v.model} ${t.part}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>({Scaduto:0,'In scadenza':1,Regolare:2}[a.d.status]-{Scaduto:0,'In scadenza':1,Regolare:2}[b.d.status]));}
function empty(title,text,action,label){return `<div class="empty"><span class="empty-icon">＋</span><h3>${title}</h3><p>${text}</p>${action?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`}
function render(){const all=data.tasks.map(t=>due(t,vehicle(t.vehicleId)));const late=all.filter(d=>d.status==='Scaduto').length,soon=all.filter(d=>d.status==='In scadenza').length;
app.innerHTML=`<aside><a class="brand" href="#"><span class="brand-mark">L</span>LiftCare</a><div class="aside-label">OFFICINA / FLOTTA</div><nav>${[['overview','▦','Panoramica'],['fleet','▤','Muletti'],['plans','◷','Piani manutenzione'],['history','↺','Storico interventi']].map(([id,icon,name])=>`<button data-view="${id}" class="${view===id?'active':''}"><span>${icon}</span>${name}</button>`).join('')}</nav><div class="aside-bottom"><span class="live"></span> Archivio locale<div class="storage-text">Dati salvati su questo browser</div><button data-action="export">Esporta backup</button><button data-action="import">Importa backup</button></div></aside><main><header><div><span class="eyebrow">GESTIONE MANUTENZIONE</span><h1>${{overview:'La tua flotta, sotto controllo.',fleet:'Muletti',plans:'Piani manutenzione',history:'Storico interventi'}[view]}</h1></div><button class="primary" data-action="${view==='fleet'?'vehicle':'service'}">＋ ${view==='fleet'?'Nuovo muletto':'Registra intervento'}</button></header>${startupError?`<div class="warning">${startupError}</div>`:''}
${view==='overview'?`<section class="stats"><article><span>Muletti in flotta</span><strong>${data.vehicles.length.toString().padStart(2,'0')}</strong><small>Anagrafiche attive</small></article><article class="alert-stat"><span>Interventi scaduti</span><strong>${late.toString().padStart(2,'0')}</strong><small>Da programmare</small></article><article><span>In scadenza</span><strong>${soon.toString().padStart(2,'0')}</strong><small>Entro 30 giorni o soglia ore</small></article><article><span>Costi registrati</span><strong class="cost">${money(data.history.reduce((n,h)=>n+h.cost,0))}</strong><small>${data.history.length} interventi eseguiti</small></article></section>`:''}
${view==='overview'||view==='plans'?`<section class="panel"><div class="panel-top"><div><h2>${view==='overview'?'Scadenziario':'Interventi programmati'}</h2><p>La prima soglia raggiunta, per data o ore, determina la scadenza.</p></div><button data-action="plan">＋ Nuovo piano</button></div><div class="toolbar"><input id="search" placeholder="Cerca muletto, intervento o ricambio…" aria-label="Cerca" value="${esc(query)}"><select id="filter" aria-label="Filtra muletto"><option value="all">Tutti i muletti</option>${data.vehicles.map(v=>`<option value="${esc(v.id)}" ${filter===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></div><div id="table">${taskTable()}</div></section><div class="hint">Gli intervalli vanno impostati secondo il manuale del costruttore e le condizioni di utilizzo.</div>`:''}
${view==='fleet'?fleetHTML():''}${view==='history'?historyHTML():''}<footer>LiftCare <span>Manutenzione · Tagliandi · Ricambi</span></footer></main>`;
app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id));
const search=app.querySelector('#search');if(search)search.oninput=e=>{query=e.target.value;app.querySelector('#table').innerHTML=taskTable();bindTable()};const select=app.querySelector('#filter');if(select)select.onchange=e=>{filter=e.target.value;render()};}
function taskTable(){const list=rows();return list.length?`<div class="table-scroll"><table><thead><tr><th>Muletto / intervento</th><th>Stato</th><th>Prossima scadenza</th><th>Ultimo intervento</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><strong>${esc(t.name)}</strong><small>${esc(t.v.name)}${t.part?' · '+esc(t.part):''}</small></td><td>${badge(t.d.status)}</td><td><strong>${t.d.hours!==null?`${t.d.hours} h`:''}${t.d.hours!==null&&t.d.day?' / ':''}${t.d.day?date(t.d.day):''}</strong><small>${t.d.remaining!==null?`${t.d.remaining>=0?'Mancano':'Superate'} ${Math.abs(t.d.remaining)} h`:'Scadenza a calendario'}</small></td><td>${date(t.lastDate)}<small>${t.lastHours} h</small></td><td class="actions"><button data-action="service" data-id="${t.vehicleId}">Registra</button><button data-action="plan" data-id="${t.id}" aria-label="Modifica ${esc(t.name)}">Modifica</button></td></tr>`).join('')}</tbody></table></div>`:empty(data.tasks.length?'Nessun risultato':'Nessuna scadenza impostata',data.vehicles.length?'Aggiungi tagliandi, cambio olio, filtri e controlli con i tuoi intervalli.':'Inserisci il primo muletto per iniziare a pianificare gli interventi.',data.vehicles.length?'plan':'vehicle',data.vehicles.length?'Crea piano':'Aggiungi muletto');}
function bindTable(){app.querySelectorAll('#table [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset.id))}
function fleetHTML(){return data.vehicles.length?`<section class="fleet-grid">${data.vehicles.map(v=>{const plans=data.tasks.filter(t=>t.vehicleId===v.id);const states=plans.map(t=>due(t,v).status);return `<article class="vehicle-card"><div class="card-top"><span class="vehicle-label">${esc(v.power)}</span>${badge(states.includes('Scaduto')?'Scaduto':states.includes('In scadenza')?'In scadenza':'Regolare')}</div><h2>${esc(v.name)}</h2><p>${esc(v.model)}</p><div class="hour-meter"><strong>${v.hours.toLocaleString('it-IT')}</strong><span>ore di lavoro</span></div><dl><dt>Matricola</dt><dd>${esc(v.serial)||'—'}</dd><dt>Piani attivi</dt><dd>${plans.length}</dd></dl><div class="card-actions"><button data-action="hours" data-id="${v.id}">Aggiorna ore</button><button data-action="vehicle" data-id="${v.id}">Modifica</button></div></article>`}).join('')}</section>`:empty('La flotta parte da qui','Aggiungi modello, matricola e contatore ore dei tuoi muletti.','vehicle','Aggiungi muletto')}
function historyHTML(){return data.history.length?`<section class="panel"><div class="panel-top"><h2>Registro lavori</h2><button data-action="csv">Esporta CSV</button></div><div class="table-scroll"><table><thead><tr><th>Data / muletto</th><th>Interventi e ricambi</th><th>Ore</th><th>Tecnico e note</th><th>Costo</th></tr></thead><tbody>${data.history.map(h=>`<tr><td><strong>${date(h.date)}</strong><small>${esc(h.vehicleName)}</small></td><td>${h.items.map(i=>`<div>${esc(i.name)}${i.part?`<small>${esc(i.part)}</small>`:''}</div>`).join('')}</td><td>${h.hours} h</td><td>${esc(h.technician)||'—'}<small>${esc(h.notes)}</small></td><td>${money(h.cost)}</td></tr>`).join('')}</tbody></table></div></section>`:empty('Nessun intervento registrato','Quando completi un tagliando, trovi qui lavori, ricambi e costi.','service','Registra intervento')}
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const options=selected=>data.vehicles.map(v=>`<option value="${v.id}" ${v.id===selected?'selected':''}>${esc(v.name)}</option>`).join('');
function modal(title,body,save,after){dialog.innerHTML=`<form><div class="modal-head"><h2>${title}</h2><button type="button" id="close" aria-label="Chiudi">×</button></div><div class="form-body">${body}<p id="form-error" role="alert"></p></div><div class="modal-foot"><button type="button" id="cancel">Annulla</button><button class="primary" type="submit">Salva</button></div></form>`;dialog.querySelector('#close').onclick=dialog.querySelector('#cancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));const next=save(f,e.target);if(persist(next)){dialog.close();toast('Salvato correttamente.')}}catch(err){dialog.querySelector('#form-error').textContent=err.message}};dialog.showModal();after?.();}
function action(kind,id){
 if(kind==='vehicle'){const v=vehicle(id)||{hours:0};modal(id?'Modifica muletto':'Nuovo muletto',`${field('name','Nome / codice flotta',v.name,'text','required maxlength="80"')}${field('model','Marca e modello',v.model,'text','required maxlength="100"')}${field('serial','Matricola',v.serial,'text','maxlength="100"')}<label>Alimentazione<select name="power">${['Diesel','GPL','Elettrico','Altro'].map(p=>`<option ${v.power===p?'selected':''}>${p}</option>`).join('')}</select></label>${field('hours','Contatore ore',v.hours,'number',`required min="${v.hours}" step="0.1"`)}`,f=>{const n=structuredClone(data);const entry={...f,hours:Number(f.hours),id:id||crypto.randomUUID()};if(n.vehicles.some(x=>x.id!==id&&x.name.toLowerCase()===f.name.trim().toLowerCase()))throw Error('Nome già presente.');entry.name=f.name.trim();if(!entry.name)throw Error('Inserisci un nome.');if(id)n.vehicles[n.vehicles.findIndex(x=>x.id===id)]=entry;else n.vehicles.push(entry);return n});}
 if(kind==='hours'){const v=vehicle(id);modal('Aggiorna contatore',`<p>${esc(v.name)} · Contatore attuale: ${v.hours} h</p>${field('hours','Ore attuali',v.hours,'number',`required min="${v.hours}" step="0.1"`)}`,f=>{const n=structuredClone(data);n.vehicles.find(v=>v.id===id).hours=Number(f.hours);return n});}
 if(kind==='plan'){if(!data.vehicles.length){toast('Aggiungi prima un muletto.');return}const t=data.tasks.find(t=>t.id===id)||{vehicleId:filter==='all'?data.vehicles[0].id:filter,hours:0,months:0,lastHours:0,lastDate:today()};modal(id?'Modifica piano':'Nuovo piano manutenzione',`<label>Muletto<select name="vehicleId" ${id?'disabled':''}>${options(t.vehicleId)}</select></label>${field('name','Intervento',t.name,'text','required list="jobs" maxlength="100"')}<datalist id="jobs">${['Tagliando completo','Cambio olio motore','Filtro olio','Filtro aria','Filtro carburante','Olio e filtro idraulico','Ingrassaggio','Controllo batteria','Controllo catene e forche'].map(s=>`<option value="${s}">`).join('')}</datalist>${field('part','Codice ricambio / filtro',t.part,'text','maxlength="120"')}<div class="form-grid">${field('hours','Ogni ore (0 = disattivato)',t.hours,'number','required min="0" step="0.1"')}${field('months','Ogni mesi (0 = disattivato)',t.months,'number','required min="0" step="1"')}</div><p class="help">Imposta almeno una frequenza. Le soglie ore e mesi sono alternative: vale quella raggiunta prima.</p><div class="form-grid">${field('lastDate','Ultimo intervento / data iniziale',t.lastDate,'date',`required max="${today()}"`)}${field('lastHours','Ore ultimo intervento / iniziali',t.lastHours,'number','required min="0" step="0.1"')}</div>${id?'<button type="button" id="delete-plan" class="danger">Elimina piano</button>':''}`,f=>{const n=structuredClone(data);const entry={...f,vehicleId:id?t.vehicleId:f.vehicleId,id:id||crypto.randomUUID(),hours:Number(f.hours),months:Number(f.months),lastHours:Number(f.lastHours)};entry.name=entry.name.trim();if(!entry.name)throw Error('Inserisci un intervento.');if(!(entry.hours||entry.months))throw Error('Imposta una frequenza in ore o mesi.');if(entry.lastHours>vehicle(entry.vehicleId).hours)throw Error('Le ore iniziali superano il contatore del muletto.');if(id)n.tasks[n.tasks.findIndex(x=>x.id===id)]=entry;else n.tasks.push(entry);return n},()=>{if(id)dialog.querySelector('#delete-plan').onclick=()=>{if(confirm('Eliminare questo piano? Lo storico degli interventi verrà conservato.')){const n=structuredClone(data);n.tasks=n.tasks.filter(x=>x.id!==id);if(persist(n))dialog.close()}}});}
 if(kind==='service'){if(!data.tasks.length){toast('Crea prima un piano manutenzione.');return}const selected=id||data.tasks[0].vehicleId;modal('Registra intervento',`<label>Muletto<select name="vehicleId" id="service-vehicle">${options(selected)}</select></label><div id="service-tasks"></div><div class="form-grid">${field('date','Data intervento',today(),'date',`required max="${today()}"`)}${field('hours','Ore al momento dell’intervento',vehicle(selected).hours,'number',`required min="${vehicle(selected).hours}" step="0.1"`)}</div>${field('technician','Tecnico / officina','','text','maxlength="120"')}${field('cost','Costo totale (€)',0,'number','required min="0" step="0.01"')}<label>Note e ricambi utilizzati<textarea name="notes" rows="3" maxlength="2000"></textarea></label>`,(f,form)=>complete(data,f.vehicleId,[...form.querySelectorAll('[name="tasks"]:checked')].map(c=>c.value),{date:f.date,hours:Number(f.hours),cost:Number(f.cost),technician:f.technician,notes:f.notes}),()=>{const update=()=>{const vid=dialog.querySelector('#service-vehicle').value;dialog.querySelector('#service-tasks').innerHTML=`<fieldset><legend>Lavori eseguiti</legend>${data.tasks.filter(t=>t.vehicleId===vid).map(t=>`<label class="check"><input type="checkbox" name="tasks" value="${t.id}"><span>${esc(t.name)}<small>${esc(t.part)}</small></span></label>`).join('')||'<p>Nessun piano per questo muletto.</p>'}</fieldset>`;dialog.querySelector('[name="hours"]').value=vehicle(vid).hours;dialog.querySelector('[name="hours"]').min=vehicle(vid).hours};dialog.querySelector('#service-vehicle').onchange=update;update()});}
 if(kind==='export'){download('liftcare-backup-'+today()+'.json',startupError?localStorage.getItem(KEY):JSON.stringify(data,null,2),'application/json');}
 if(kind==='import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>10000000)throw Error('Backup troppo grande (massimo 10 MB).');const next=validateBackup(JSON.parse(await file.text()));if(confirm('Importare il backup? I dati presenti saranno sostituiti. Esporta prima una copia se vuoi conservarli.')){if(persist(next,true)){startupError='';filter='all';render();toast('Backup importato.')}}}catch(e){toast(e.message)}};input.click();}
 if(kind==='csv'){const cell=s=>'"'+String(s).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Data','Muletto','Interventi','Ricambi','Ore','Tecnico','Costo EUR','Note'],...data.history.map(h=>[h.date,h.vehicleName,h.items.map(i=>i.name).join(' | '),h.items.map(i=>i.part).join(' | '),h.hours,h.technician,h.cost,h.notes])];download('liftcare-interventi.csv','\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');}
}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.addEventListener('storage',e=>{if(e.key===KEY){try{data=e.newValue?validateBackup(JSON.parse(e.newValue)):blank();dialog.close();render();toast('Archivio aggiornato da un’altra scheda.')}catch{toast('Dati aggiornati non validi. Ricarica dopo aver verificato il backup.')}}});render();
