import {LiftCareBackend} from './backend.js?v=4';
import {validateBackup} from './domain.js?v=4';
export const api=new LiftCareBackend({url:'https://tkugxpgljwcnndjsmhjq.supabase.co',publishableKey:'sb_publishable_SeENF7vcFSV73GPFmvNGWw_DkBQ7xla'});
const SESSION='liftcare-session-v1';
export function saveSession(){if(api.session)sessionStorage.setItem(SESSION,JSON.stringify(api.session));else sessionStorage.removeItem(SESSION)}
export async function restoreSession(){try{api.session=JSON.parse(sessionStorage.getItem(SESSION)||'null');if(api.session){await api.refreshSession();saveSession()}}catch{api.session=null;saveSession()}}
let refreshing;
export async function ensureSession(){if(!api.session)throw Error('Accedi per usare il tuo archivio online.');if(!api.session.expires_at||api.session.expires_at*1000<Date.now()+60000){refreshing??=api.refreshSession().then(saveSession).catch(e=>{api.session=null;saveSession();throw e}).finally(()=>{refreshing=null});await refreshing}}
async function all(table){let result=[],offset=0;for(;;){const page=await api.list(table,{offset,limit:1000});result.push(...page);if(page.length<1000)return result;offset+=page.length}}
export async function loadCloud(){await ensureSession();const [machines,plans,records]=await Promise.all([all('machines'),all('maintenance_plans'),all('service_records')]);const history=[];for(const h of records){const photos=await api.listPhotos(h.id);history.push({id:h.id,vehicleId:h.machine_id,vehicleName:h.machine_name,vehicleType:h.machine_type,unit:h.unit,date:h.date,reading:Number(h.reading),cost:Number(h.cost),technician:h.technician,notes:h.notes,items:h.items,photos:[],photoFiles:photos.filter(p=>p.id).map(p=>p.name)});}history.sort((a,b)=>b.date.localeCompare(a.date));return validateBackup({version:2,vehicles:machines.map(({id,name,type,model,serial,plate,power,unit,reading})=>({id,name,type,model,serial,plate,power,unit,reading:Number(reading)})),tasks:plans.map(p=>({id:p.id,vehicleId:p.machine_id,name:p.name,part:p.part,interval:Number(p.interval),months:p.months,lastReading:Number(p.last_reading),lastDate:p.last_date})),history})}
const machine=v=>({id:v.id,name:v.name,type:v.type,model:v.model,serial:v.serial,plate:v.plate,power:v.power,unit:v.unit,reading:v.reading});
const plan=t=>({id:t.id,machine_id:t.vehicleId,name:t.name,part:t.part,interval:t.interval,months:t.months,last_reading:t.lastReading,last_date:t.lastDate});
export async function saveChanges(old,next){await ensureSession();validateBackup(next);if(JSON.stringify(old.history)!==JSON.stringify(next.history))throw Error('Lo storico si registra tramite il modulo intervento.');for(const [key,table,map] of [['vehicles','machines',machine],['tasks','maintenance_plans',plan]]){for(const row of next[key]){const prior=old[key].find(x=>x.id===row.id);if(JSON.stringify(prior)!==JSON.stringify(row)){const values=map(row);if(prior)delete values.id;await api.write(table,values,prior?.id)}}}for(const row of old.tasks)if(!next.tasks.some(x=>x.id===row.id))await api.remove('maintenance_plans',row.id);return loadCloud()}
export async function uploadPhotos(id,photos){await ensureSession();for(let i=0;i<photos.length;i++){const response=await fetch(photos[i].dataUrl);await api.uploadPhoto(id,i+1,await response.blob())}}
export async function recordCloud(values,photos){await ensureSession();const record=await api.recordService(values);let photoError='';try{await uploadPhotos(record.id,photos)}catch(e){photoError='Intervento salvato, ma alcune foto non sono state caricate: '+e.message;}let data=null,reloadError='';try{data=await loadCloud()}catch(e){reloadError='Intervento salvato online. Aggiorna dal cloud per rileggere l’archivio: '+e.message}return {cloudSaved:true,data,photoError,reloadError,recordId:record.id,pendingPhotos:photoError?photos:[]}}
export async function readPhotos(h){await ensureSession();const result=[];for(const file of h.photoFiles||[]){const [slot,extension]=file.split('.');const path=api.photoPath(h.id,Number(slot),extension);const response=await fetch(api.url+'/storage/v1/object/authenticated/liftcare-photos/'+path,{headers:{apikey:api.key,Authorization:'Bearer '+api.session.access_token}});if(!response.ok)throw Error('Download foto non riuscito.');const blob=await response.blob();const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)});result.push({name:file,dataUrl})}return result}
export async function exportCloud(data){const copy=structuredClone(data);for(const h of copy.history){h.photos=await readPhotos(h);delete h.photoFiles}return copy}
export async function importCloud(data){await ensureSession();validateBackup(data);await api.request('/rest/v1/rpc/import_archive',{method:'POST',body:{archive:data}});let failures=0;for(const h of data.history){try{await uploadPhotos(h.id,h.photos||[])}catch{failures++}}return {data:await loadCloud(),failures}}
export async function retryPhotos(id,photos){await ensureSession();const present=await api.listPhotos(id);for(let i=0;i<photos.length;i++){if(present.some(p=>p.id&&p.name.startsWith((i+1)+'.')))continue;const r=await fetch(photos[i].dataUrl);await api.uploadPhoto(id,i+1,await r.blob())}return loadCloud()}

export async function accessStatus(){await ensureSession();return api.request('/rest/v1/rpc/access_status',{method:'POST',body:{}})}
