import {createSessionManager,SESSION_KEY} from './session.js?v=9';
export {SESSION_KEY};
import {photoBlob} from './photos.js?v=9';
import {LiftCareBackend} from './backend.js?v=9';
import {validateBackup} from './domain.js?v=9';
export const api=new LiftCareBackend({url:'https://tkugxpgljwcnndjsmhjq.supabase.co',publishableKey:'sb_publishable_SeENF7vcFSV73GPFmvNGWw_DkBQ7xla'});
const sessions=createSessionManager({api,storage:globalThis.localStorage,legacyStorage:globalThis.sessionStorage,locks:globalThis.navigator?.locks});
export const saveSession=sessions.save,clearSavedSession=sessions.clear,restoreSession=sessions.restore,ensureSession=sessions.ensure;
async function all(table){let result=[],offset=0;for(;;){const page=await api.list(table,{offset,limit:1000});result.push(...page);if(page.length<1000)return result;offset+=page.length}}
export async function loadCloud(){await ensureSession();const [machines,plans,records,inventory,deadlines,preferences]=await Promise.all([all('machines'),all('maintenance_plans'),all('service_records'),api.request('/rest/v1/rpc/photo_inventory',{method:'POST',body:{}}),all('vehicle_deadlines'),api.request('/rest/v1/rpc/reminder_status',{method:'POST',body:{}})]);const history=[];for(const h of records){const photos=inventory[h.id]||[];history.push({id:h.id,vehicleId:h.machine_id,vehicleName:h.machine_name,vehicleType:h.machine_type,unit:h.unit,date:h.date,reading:Number(h.reading),cost:Number(h.cost),technician:h.technician,notes:h.notes,items:h.items,photos:[],photoFiles:photos});}history.sort((a,b)=>b.date.localeCompare(a.date));return validateBackup({version:2,deadlines:deadlines.map(d=>({id:d.id,vehicleId:d.machine_id,kind:d.kind,dueDate:d.due_date,notify:d.notify,notes:d.notes})),emailNotifications:preferences.enabled,vehicles:machines.map(({id,name,type,model,serial,plate,power,unit,reading})=>({id,name,type,model,serial,plate,power,unit,reading:Number(reading)})),tasks:plans.map(p=>({id:p.id,vehicleId:p.machine_id,name:p.name,part:p.part,interval:Number(p.interval),months:p.months,lastReading:Number(p.last_reading),lastDate:p.last_date})),history})}
const machine=v=>({id:v.id,name:v.name,type:v.type,model:v.model,serial:v.serial,plate:v.plate,power:v.power,unit:v.unit,reading:v.reading});
const deadline=d=>({id:d.id,machine_id:d.vehicleId,kind:d.kind,due_date:d.dueDate,notify:d.notify,notes:d.notes});
const plan=t=>({id:t.id,machine_id:t.vehicleId,name:t.name,part:t.part,interval:t.interval,months:t.months,last_reading:t.lastReading,last_date:t.lastDate});
export async function saveChanges(old,next){await ensureSession();validateBackup(next);if(JSON.stringify(old.history)!==JSON.stringify(next.history))throw Error('Lo storico si registra tramite il modulo intervento.');for(const [key,table,map] of [['vehicles','machines',machine],['tasks','maintenance_plans',plan],['deadlines','vehicle_deadlines',deadline]]){for(const row of next[key]||[]){const prior=(old[key]||[]).find(x=>x.id===row.id);if(JSON.stringify(prior)!==JSON.stringify(row)){const values=map(row);if(prior)delete values.id;await api.write(table,values,prior?.id)}}}for(const row of old.tasks)if(!next.tasks.some(x=>x.id===row.id))await api.remove('maintenance_plans',row.id);for(const row of old.deadlines||[])if(!next.deadlines.some(x=>x.id===row.id))await api.remove('vehicle_deadlines',row.id);if(old.emailNotifications!==next.emailNotifications)await api.request('/rest/v1/rpc/set_reminder_preference',{method:'POST',body:{enabled:next.emailNotifications}});return loadCloud()}
export async function uploadPhotos(id,photos){await ensureSession();if(photos.length){const usage=await storageUsage();if(usage.used_bytes+photos.length*160000>usage.limit_bytes)throw Error('Spazio foto gratuito esaurito. Rimuovi foto per liberare spazio.');}for(let i=0;i<photos.length;i++){await api.uploadPhoto(id,i+1,photoBlob(photos[i]))}}
export async function recordCloud(values,photos){await ensureSession();const record=await api.recordService(values);let photoError='';try{await uploadPhotos(record.id,photos)}catch(e){photoError='Intervento salvato, ma alcune foto non sono state caricate: '+e.message;}let data=null,reloadError='';try{data=await loadCloud()}catch(e){reloadError='Intervento salvato online. Aggiorna dal cloud per rileggere l’archivio: '+e.message}return {cloudSaved:true,data,photoError,reloadError,recordId:record.id,pendingPhotos:photoError?photos:[]}}
export async function readPhotos(h){await ensureSession();const result=[];for(const file of h.photoFiles||[]){const [slot,extension]=file.split('.');const path=api.photoPath(h.id,Number(slot),extension);const response=await fetch(api.url+'/storage/v1/object/authenticated/liftcare-photos/'+path,{headers:{apikey:api.key,Authorization:'Bearer '+api.session.access_token}});if(!response.ok)throw Error('Download foto non riuscito.');const blob=await response.blob();const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)});result.push({name:file,dataUrl})}return result}
export async function exportCloud(data){const copy=structuredClone(data);for(const h of copy.history){h.photos=await readPhotos(h);delete h.photoFiles}return copy}
export async function importCloud(data){await ensureSession();validateBackup(data);await api.request('/rest/v1/rpc/import_archive',{method:'POST',body:{archive:{...data,history:data.history.map(({photos,photoFiles,...h})=>h)}}});let failures=0;for(const h of data.history){try{await uploadPhotos(h.id,h.photos||[])}catch{failures++}}return {data:await loadCloud(),failures}}
export async function retryPhotos(id,photos){await ensureSession();const present=await api.listPhotos(id);for(let i=0;i<photos.length;i++){if(present.some(p=>p.id&&p.name.startsWith((i+1)+'.')))continue;await api.uploadPhoto(id,i+1,photoBlob(photos[i]))}return loadCloud()}

export async function accessStatus(){await ensureSession();return api.request('/rest/v1/rpc/access_status',{method:'POST',body:{}})}

export async function storageUsage(){await ensureSession();return api.request('/rest/v1/rpc/photo_usage',{method:'POST',body:{}})}
